# This is a basic workflow to help you get started with Actions

name: Test Build, Test, Deploy - To UAT 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # schedule:
  #  - cron: '30 19 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  REACT_APP_BASE_API: ${{secrets.REACT_APP_BASE_API_UAT}}
  REACT_APP_LOGOUT_URL: ${{secrets.LOGOUT_URL_UAT}}
  REACT_APP_RESEARCHER_AUTH_URL: ${{secrets.RESEARCHER_AUTH_URL_UAT}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dte
    # strategy:
    #   matrix:
    #     node-version: [8.x, 10.x, 12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Configure AWS credentials - All
        # if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_VS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_VS_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Yarn Install
        run: yarn install
      - name: Runing  ESLint
        run: yarn lintnofix
      - name: Build Files
        run: yarn build
      - name: Running Unit Tests
        run: yarn test
     

      - name: Deploy to S3 - UAT
        shell: bash
        run: |
          aws s3 sync ./build/ s3://$AWS_S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[0] == '${{ secrets.VS_NIHR_URL_UAT }}'].Id" --output text) --paths '/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_UAT_BUCKET_NAME }}

